source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

#install! 'cocoapods', disable_input_output_paths: true, generate_multiple_pod_projects: true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
      
      if config.name != 'Release'
        if target.name == 'SJBaseVideoPlayer'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) SJDEBUG'
        end
      end
    end
  end
  
#  installer.pod_target_subprojects.each do |project|
#    project.targets.each do |target|
#      target.build_configurations.each do |config|
#        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
#          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#        end
#      end
#    end
#  end
end


target 'SJVideoPlayer_Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SJVideoPlayer

  pod 'SJBaseVideoPlayer'#, :path => '../../SJBaseVideoPlayer'
  pod 'SJVideoPlayer', :path => '../../SJVideoPlayer'
  
#  pod 'ijkplayerssl', :git => 'https://gitee.com/changsanjiang/ijkplayer.git'
  
  # 全屏手势
  pod 'SJFullscreenPopGesture/ObjC'
  pod 'SJPlaybackListController'#, :path => '../../SJPlaybackListController'
  pod 'Masonry', :inhibit_warnings => true
  pod 'MJRefresh', :inhibit_warnings => true
  pod 'SJRouter'
  pod 'SJUIKit'
  pod 'SDWebImage'
end
