# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SJVideoPlayerProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SJVideoPlayerProject

    pod 'Masonry'
    pod 'SJFullscreenPopGesture'
    pod 'SJOrentationObserver'
    pod 'SJVideoPlayerAssetCarrier'
    pod 'SJVolBrigControl'
    pod 'SJUIFactory'
    pod 'SJSlider'
    pod 'SJAttributesFactory'
    pod 'SJObserverHelper'
    pod 'SJPrompt'
    pod 'SJLoadingView'
    pod 'SJLabel'
end
