//
//  SJVideoPlayerLocalizedStringKeys.h
//  Pods
//
//  Created by 畅三江 on 2019/11/27.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN 

///
/// 本地化
///
typedef NSString * SJVideoPlayerLocalizedStringKey;

UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyLongPressSpeedupPlayback;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyNoNetwork;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyWiFiNetWork;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyCellularNetwork;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyReplay;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyRetry;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyReload; 
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyLiveBroadcast;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyCancel;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyDone;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyUnstableNetworkPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyCellularNetworkPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyNoNetworkPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyPlaybackFailedPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyRecordsPreparingPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyRecordsToFinishRecordingPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyExportsExportingPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyExportsExportFailedPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyExportsExportSuccessfullyPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyUploadsUploadingPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyUploadsUploadFailedPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyUploadsUploadSuccessfullyPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyScreenshotSuccessfullyPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyAlbumAuthDeniedPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyAlbumSavingScreenshotToAlbumPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyAlbumSavedToAlbumPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyOperationFailedPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyDefinitionSwitchingPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyDefinitionSwitchSuccessfullyPrompt;
UIKIT_EXTERN SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyDefinitionSwitchFailedPrompt;
NS_ASSUME_NONNULL_END
