//
//  SJVideoPlayerLocalizedStringKeys.m
//  Pods
//
//  Created by 畅三江 on 2019/11/27.
//

#import "SJVideoPlayerLocalizedStringKeys.h"

NS_ASSUME_NONNULL_BEGIN 

#if 0
(UIKIT_EXTERN\s)(SJVideoPlayerLocalizedStringKey\sconst\s)([^;]+)
$2$3 = @"$3"
#endif

SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyLongPressSpeedupPlayback = @"SJVideoPlayerLocalizedStringKeyLongPressSpeedupPlayback";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyNoNetwork = @"SJVideoPlayerLocalizedStringKeyNoNetwork";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyWiFiNetWork = @"SJVideoPlayerLocalizedStringKeyWiFiNetWork";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyCellularNetwork = @"SJVideoPlayerLocalizedStringKeyCellularNetwork";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyReplay = @"SJVideoPlayerLocalizedStringKeyReplay";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyRetry = @"SJVideoPlayerLocalizedStringKeyRetry";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyReload = @"SJVideoPlayerLocalizedStringKeyReload"; 
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyLiveBroadcast = @"SJVideoPlayerLocalizedStringKeyLiveBroadcast";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyCancel = @"SJVideoPlayerLocalizedStringKeyCancel";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyDone = @"SJVideoPlayerLocalizedStringKeyDone";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyUnstableNetworkPrompt = @"SJVideoPlayerLocalizedStringKeyUnstableNetworkPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyCellularNetworkPrompt = @"SJVideoPlayerLocalizedStringKeyCellularNetworkPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyNoNetworkPrompt = @"SJVideoPlayerLocalizedStringKeyNoNetworkPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyPlaybackFailedPrompt = @"SJVideoPlayerLocalizedStringKeyPlaybackFailedPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyRecordsPreparingPrompt = @"SJVideoPlayerLocalizedStringKeyRecordsPreparingPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyRecordsToFinishRecordingPrompt = @"SJVideoPlayerLocalizedStringKeyRecordsToFinishRecordingPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyExportsExportingPrompt = @"SJVideoPlayerLocalizedStringKeyExportsExportingPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyExportsExportFailedPrompt = @"SJVideoPlayerLocalizedStringKeyExportsExportFailedPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyExportsExportSuccessfullyPrompt = @"SJVideoPlayerLocalizedStringKeyExportsExportSuccessfullyPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyUploadsUploadingPrompt = @"SJVideoPlayerLocalizedStringKeyUploadsUploadingPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyUploadsUploadFailedPrompt = @"SJVideoPlayerLocalizedStringKeyUploadsUploadFailedPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyUploadsUploadSuccessfullyPrompt = @"SJVideoPlayerLocalizedStringKeyUploadsUploadSuccessfullyPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyScreenshotSuccessfullyPrompt = @"SJVideoPlayerLocalizedStringKeyScreenshotSuccessfullyPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyAlbumAuthDeniedPrompt = @"SJVideoPlayerLocalizedStringKeyAlbumAuthDeniedPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyAlbumSavingScreenshotToAlbumPrompt = @"SJVideoPlayerLocalizedStringKeyAlbumSavingScreenshotToAlbumPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyAlbumSavedToAlbumPrompt = @"SJVideoPlayerLocalizedStringKeyAlbumSavedToAlbumPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyOperationFailedPrompt = @"SJVideoPlayerLocalizedStringKeyOperationFailedPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyDefinitionSwitchingPrompt = @"SJVideoPlayerLocalizedStringKeyDefinitionSwitchingPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyDefinitionSwitchSuccessfullyPrompt = @"SJVideoPlayerLocalizedStringKeyDefinitionSwitchSuccessfullyPrompt";
SJVideoPlayerLocalizedStringKey const SJVideoPlayerLocalizedStringKeyDefinitionSwitchFailedPrompt = @"SJVideoPlayerLocalizedStringKeyDefinitionSwitchFailedPrompt";
NS_ASSUME_NONNULL_END
