# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
end

target 'SJVideoPlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SJVideoPlayer

  #pod 'SJBaseVideoPlayer', :path => '../../SJBaseVideoPlayer'
  pod 'SJVideoPlayer', :path => '../../SJVideoPlayer'
  
  
  # 全屏手势
  pod 'SJFullscreenPopGesture'
  pod 'SJPlaybackListController'#, :path => '../../SJPlaybackListController'
  pod 'SJScrollEntriesView'
  pod 'Masonry', :inhibit_warnings => true
  pod 'MJRefresh', :inhibit_warnings => true
  pod 'SJRouter'
  pod 'SJScrollEntriesView'
  pod 'SJUIKit'
  #pod 'MJRefresh', :inhibit_warnings => true
end
