//
//  SJVideoPlayerConst.h
//  Pods
//
//  Created by 畅三江 on 2019/11/27.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN
extern NSTimeInterval const CommonAnimaDuration;

///
/// 本地化
///
typedef NSString * SJVideoPlayerLocalizedString;
/// 边缘控制层
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_FastForwardFFText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_ReplayButtonTitle;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_UnstableNetworkPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_CellularNetworkPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_LiveText;
// 自定义的状态栏
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_StatusBarNoNetworkText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_StatusBarWiFiText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_StatusBarCellularNetworkText;

/// 播放失败控制层
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_PlayFailedPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_PlayFailedButtonTitle;

/// 无网控制层
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_NoNetworkPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_NoNetworkReloadButtonTitle;

/// 剪辑控制层
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_CancelButtonTitle;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_DoneButtonTitle;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_WaitingPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_FinishedPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_ExportingPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_ExportFailedPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_ExportSucceededPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_ScreenshotSucceededPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_AlbumAuthDeniedPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_SavingToAlbumPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_SavedToAlbumPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_UplodingPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_UploadFailedPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_UploadSucceededPromptText;
UIKIT_EXTERN SJVideoPlayerLocalizedString const SJVideoPlayer_OperationFailedPromptText;
NS_ASSUME_NONNULL_END
