# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SJVideoPlayerV3Project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
["SJBaseVideoPlayer",
 "SJAttributesFactory",
 "SJFullscreenPopGesture",
 "SJLoadingView",
 "SJSlider"
 ].each {|lib| pod lib}
 
  # Pods for SJVideoPlayerV3Project

  target 'SJVideoPlayerV3ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SJVideoPlayerV3ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
